# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/_Pose.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/_Pose.proto',
  package='test',
  serialized_pb=_b('\n\x14protobuf/_Pose.proto\x12\x04test\"n\n\x04Pose\x1a+\n\x08position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\x39\n\x0borientation\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POSE_POSITION = _descriptor.Descriptor(
  name='position',
  full_name='test.Pose.position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='test.Pose.position.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='test.Pose.position.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='test.Pose.position.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=81,
)

_POSE_ORIENTATION = _descriptor.Descriptor(
  name='orientation',
  full_name='test.Pose.orientation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='test.Pose.orientation.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='test.Pose.orientation.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='test.Pose.orientation.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='test.Pose.orientation.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=140,
)

_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='test.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_POSE_POSITION, _POSE_ORIENTATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=140,
)

_POSE_POSITION.containing_type = _POSE
_POSE_ORIENTATION.containing_type = _POSE
DESCRIPTOR.message_types_by_name['Pose'] = _POSE

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(

  position = _reflection.GeneratedProtocolMessageType('position', (_message.Message,), dict(
    DESCRIPTOR = _POSE_POSITION,
    __module__ = 'protobuf._Pose_pb2'
    # @@protoc_insertion_point(class_scope:test.Pose.position)
    ))
  ,

  orientation = _reflection.GeneratedProtocolMessageType('orientation', (_message.Message,), dict(
    DESCRIPTOR = _POSE_ORIENTATION,
    __module__ = 'protobuf._Pose_pb2'
    # @@protoc_insertion_point(class_scope:test.Pose.orientation)
    ))
  ,
  DESCRIPTOR = _POSE,
  __module__ = 'protobuf._Pose_pb2'
  # @@protoc_insertion_point(class_scope:test.Pose)
  ))
_sym_db.RegisterMessage(Pose)
_sym_db.RegisterMessage(Pose.position)
_sym_db.RegisterMessage(Pose.orientation)


# @@protoc_insertion_point(module_scope)
